
package ch10.book.exercise.p05;

public class P05 {
	public void method1() throws NumberFormatException, ClassNotFoundException{
/*		다음과 같은 메소드가 있을 때 예외를 잘못 처리한 것은 무엇입니까? 3번
 		
		
1.		try{
			method1();
		}catch(Exception e) {
			
		}
		
2.		void method2()throws Exception{
			method1();
		}
		
3.		try {
			method1();
		}catch(Exception e) {
			
		}catch(ClassNotFoundException) {
			
		}
		
4.		try {
			method1();
		}catch(Exception e) {
			
		}catch(NumberFormatException) {
			
		}				*/
		
		
	}
}
